### ISSUE TITLE
Fabric deployment hangs while attempting to generate crypto material for organization peers

### ISSUE THREAD

**Issue by anweiss** [hyperledger-labs/blockchain-automation-framework#1071]
**Describe the bug**

The deployment seems to hang during the `generate crypto material for organization peers` task. After a considerable period of time, the deployment proceeds. A closer look at the `ca-<id>-<id>` pod in the `supplychain-net` namespace reveals the following error in the logs:

```
Error: Failed to create default configuration file: An empty password in the '-b user:pass' option is not permitted
```

I am not providing any CA certs in advance nor am I using a custom external domain for this deployment. I've also verified that I was using an absolute path to the certificate directory in my orderer config, and the cert files seem to have been generated, albeit they are empty. This also causes the rest of the deployment to ultimately fail because TLS certs are never generated for the orderers and peers.

**To Reproduce**

1. Configure `network.yaml` for Hyperledger Fabric
2. Deploy playbook

**Expected behavior**

Expect task to complete with no pod errors.

**Screenshots**

N/A

**Environment (please complete the following information):**

 - OS: Ubuntu 20.04 LTS
 - Kubernetes: IBM Kubernetes Service v1.17.11
 - Version: `master` (ee2eff1405423cc5b38bf5a25613bd17c89ead16)

**Additional context**

N/A

**Comment by jagpreetsinghsasan** [comment]
This is most probably IBM K8s issue.
The CA chart uses the password from a file mounted. This error says the password is empty, which means the issue is with the storage itself.
Here's the path to the chart
blockchain-automation-framework/platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml

The file /etc/hyperledger/fabric-ca-server-config/user_cred is not present/accessible
![image](https://user-images.githubusercontent.com/56861721/94664216-44a26280-0328-11eb-9af2-83f104c55185.png)

**Comment by sownak** [comment]
Do not think this is a bug as BAF was never tested on IBM Kubernetes Service.

**Comment by anweiss** [comment]
Thanks @jagpreetsinghsasan and @sownak! Turns out this was a Vault misconfiguration on my part and nothing to do with IKS storage.  FYSA, I've been testing on IKS and have some additions I'll be pushing up in a PR related to #1001. Closing.
