### ISSUE TITLE
Manually query the deployed supplychain smartcontract on the besu network

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1238]
**Describe the bug**
The transactions send to besu network using the `eth_sendRawTransaction` is retuning empty logs witha success status.

**To Reproduce**
1. Edit Besu Network.yaml
2. Set besu network
3. Deploy the quorum sample chaincode 
4. Try to invoke `addContainer` and `getSingleContainer` functions manually.

**Expected behavior**
the log field in `getSingleContainer` should be returning the values for the new container.

**Screenshots**
![image](https://user-images.githubusercontent.com/56861637/102197572-5a670300-3ee7-11eb-9ffa-47f14a962950.png)

**Additional context**
Try emitters with solidity chaincode.

**Comment by lakshyakumar** [comment]
used js script to call invoke the smartcontract `createContainer` and `getContainer` functions using the contract `ABI` and `web3-eea.js` library for private transactions. not getting any output in the `getContainer` function result even after the transaction is successful.
Next steps include the `web3.js` library to invoke the functions using the `sendRawTransaction`.

**Comment by ragalz** [comment]
The transaction is not returning any logs since there are no events being emitted in the function _getSingleContainer_.
The function is declared as a **view** function, which means that it is supposed to be queried (use **eth_call** instead of **eth_sendRawTransaction**). The return value of a function can only be retrieved using the JSON RPC method **eth_call**.
