### ISSUE TITLE
Add new org to the existing consortium

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1297]
## Description
As a developer, I would be able to add the new organization to the existing consortium.
Currently the new organization is only added to the existing channel. 

## Reference links
1. https://rangesh.medium.com/how-to-add-an-organization-dynamically-to-existing-consortium-hyperledger-fabric-36b4c923b937
2. https://medium.com/thinkdecentralized/updating-the-consortium-definition-in-hyperledger-fabric-d1b6a9d079b0

**Comment by alvaropicazo** [comment]
While fixing the issue, I realized that the functionality of adding a new organization to the network was not working. The error that was showing up was:  BAD_REQUEST -- error applying config update to existing channel 'allchannel': error authorizing update: error validating ReadSet: proposed update requires that key [Group]  /Channel/Application be at version 1, but it is currently at version 2.

This could be happening because the syschannel is not being updated / fetched when creating a new org, so new code will be developed for this to work correctly.
