### ISSUE TITLE
Spike: Express API requirements for Besu

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1537]
### Description
As a developer I want to create the express API app for running the supplychain smartcontract end points.

Test the existing express code with BAF deployed Besu network 

### Acceptance Criteria
1. Document the changes required if any and create further issues.

**Comment by alvaropicazo** [comment]
After some doing some research, I found out that the express API that we already have for Quorum will not work for Besu because of the not supported eth_sendTransaction method (will have to use eth_sendRawTransaction which is the one that is supported for this type of network). Internally, It looks that web3 module uses eth_sendTransaction, so the most optimal solution would be to develop a new express API using most of the code we already have for the quorum one but instead of instantiating the contract with web3 module, use others which uses eth_sendRawTransaction. 

Possible alternatives:
 - Ethsigner
 - Web3-eea

**Comment by alvaropicazo** [comment]
This task will be continued on #1562
