### ISSUE TITLE
Vault Secret engine integration for Tessera

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#1551]
### Description
As a developer I want to use v2 secret engine integration for Tessera so that I can generate keys directly on Vault

Update Tessera key generation to integrate with Vault directly
Update Tessera config file to integrate directly with Vault to download keys
https://docs.tessera.consensys.net/en/21.1.1/HowTo/Generate-Keys/Hashicorp-Vault/
https://docs.tessera.consensys.net/en/21.1.1/HowTo/Configure/Keys/Hashicorp-Vault-Pairs/

### Acceptance Criteria
1. Tessera charts in Besu and Quorum updated
2. Tessera pods are running
3. Network deployment and API tests should be successful.

**Comment by sownak** [comment]
Depends on #1548 and #1549

**Comment by alvaropicazo** [comment]
The status of this issue is that we are currently generating the public and private key of tessera by using the tessera jar file (not the binary as we havent updated the code for tessera version 21.7.0 onwards, check tessera_key_mgmt helm chart). Still pending the integration of the key pair reading in the configmap of the tessera node chart. 

As there are docker images with hashicorp vault integration support, it would be great to use them so an update of the version of tessera is required. There are some differences on how to run the tessera node so some changes are required to be done in the chart as well. From 21,7,0, they are using the binary to start the node instead of the jar file as I mentioned before.

https://docs.tessera.consensys.net/en/21.7.0/HowTo/Configure/Keys/Hashicorp-Vault-Pairs/

https://hub.docker.com/layers/quorumengineering/tessera/hashicorp-21.10.0/images/sha256-b4801366aaf8b8e2770b6284f692ed374683e39a8ccc4af4dc01b59d5b8c8afa?context=explore
