### ISSUE TITLE
Shared: Flux Git over HTTPS

### ISSUE THREAD

**Issue by juraj-durech** [hyperledger-labs/blockchain-automation-framework#236]
As I developer I would like to have the option to configure Flux for pulling over HTTPS using a token as the password.

https://docs.fluxcd.io/en/1.15.0/guides/use-git-https.html

**Comment by VladimirDzamba** [comment]
The task can't be fully finished, because official Helm release of Flux Operator isn't defined to use https (username and token). Helm release of flux operator uses only ssh key. See  https://github.com/fluxcd/flux/blob/chart-0.15.0/chart/flux/templates/helm-operator-deployment.yaml and also https://docs.fluxcd.io/projects/helm-operator/en/latest/references/helmrelease-custom-resource.html#authentication-for-git-repos
We could rewrite official helm chart of flux operator but it will be other code for maintaining.

**Comment by sownak** [comment]
This is correct, though the usual flux pod can deal with https, the helm-operator cannot. The Helm operator deals with Helm chart releases. The operator watches for changes of Custom Resources of kind `HelmRelease` which we use extensively. As a result, even if we can use https for flux, we will still need the ssh key for helmoperator.
@juraj-durech  Do you think this issue can be a 'won't fix'?

**Comment by juraj-durech** [comment]
I agree, we can re-open once the Flux HelmOperator supports Git over HTTPS. It would be quite simple if they added a envFrom K8S config map support (like in the flux deployment) where we could supply the Git credentials.
