### ISSUE TITLE
Implement solo consensus in Fabric for dev environments

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#44]

**Comment by maniankara** [comment]
Hello guys, some pointers where to start on this? I am not new to fabric but looks like setting up a dev env might be a bit challenging?

**Comment by sownak** [comment]
You can use minikube by providing cloud_provider as minikube. But for this the Vault has to be local as well i.e. vault and minikube should be able to talk to each other. Also depending on your machine's memory, you have have to tone down the network to max 3 orgs

**Comment by Henni** [comment]
Solo ordering service has been deprecated in 2.0
I propose to mark this issue as _won't fix_ and continue with the Raft implementation instead.

> Support for Solo ordering service
>
> With the introduction of Raft-based ordering service in v1.4.1, it is possible
to deploy a single-node (non-production) or multi-node
Raft-based ordering service with no external dependencies.
For single-node (non-production) ordering services, utilize Raft-based ordering
service with a single node instead of Solo ordering service.
For more details see FAB-15754.

**Comment by maniankara** [comment]
hello guys, I am not finding time to contribute here. So please don't count on me.

**Comment by sownak** [comment]
As per latest Fabric 2.0 release, as solo is deprecated, we are not going to fix this issue. And we will continue with RAFT ordering with single node for dev environments.
