### ISSUE TITLE
README.md documentation is not consistent with readthedocs

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#872]
**Describe the bug**
All README.md documentation should be consistent with readthedocs so that new users are not confused.

**To Reproduce**
1. Go to `platforms/hyperledger-indy/configuration/README.md`
2. Check pre-reqs Step 1 and 2
3. This should say baf-build has to be used rather than trying to build a container.

**Expected behavior**
The Steps 1 and 2 should be combined to use baf-build instead. This should be checked for all readme.md

**Comment by abevers** [comment]
I've started this issue by beginning with Quorum, and replaced the current documentation of the prerequisites with the following:

```markdown
# Playbooks

## Getting started
This folder contains Ansible playbooks and their corresponding roles which are used to deploy Quorum on Managed Kubernetes Cluster(s).

## BAF-Build Docker container
Blockchain Automation Framework provides a Docker image that installs required software (Ansible, python, curl and others);
which will provide an out-of-the-box environment to deploy any DLT network. <br>
The image can be found [here](https://hub.docker.com/r/hyperledgerlabs/baf-build). It will be used for deployment of the Quorum network.

## Prerequisites
To deploy the Quorum network, you will need to follow these prerequisites. 
1. Build the BAF image by running the following command from the root folder of the repository:
`docker build . -t hyperledgerlabs/baf-build`. 
...etc
```

What I am unsure of, is how we should proceed next. If we want people to use the BAF-Build container to deploy the network, the whole README.md needs to be rewritten, not only step 1 or 2, correct?
Because then the Ansible commands will not be executed from the host, but by the `run.sh` command of the container.
Am I thinking in the right direction?
